### ISSUE TITLE
Revamp overall UI

### ISSUE THREAD

**Issue by jindrichbartek** [jindrichbartek/chatgpt-client-2#1]
Make it more UX-friendly.

**Comment by jindrichbartek** [comment]
Done.

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Sanbingo, @fahmi-ahmad-slash, @18-RAJAT, @hkarakaya11, @javipmc, @737069384, @lpanizza, @unclejoe, @Yu-Qi, @ARISTODE, @CootieShots, @varunsharma10, @quest313, @huazhuangnan, @lghthon, @amdgaafar, @machine-creek, @RManLuo, @K1NGY97, @Theodoricxxx, @MonkeyNetic, @xtroncode, @bowlofhotsoup, @PanPanda, @cGitHub123, @aldorl, @Mrt3383x38, @ZeqyZulhaqy, @notime2785, @yosg, @riccardogabellone, @Rafikiki77, @ruslan-korneev, @Whisker17, @rothschild86, @jeffreyhsu957, @codebestia, @ssa1101, @EzayCrafter, @dprodigalson, @alejoar, @yigitogz, @formulaRoot, @blueplanet, @erhathaway, @vaibhavbhwsr, @1617295759, @thiagomsmachado, @Shek72, @davidkarimSanjay2891, @trile127, @MamaTLeBlanc, @Dmdv, @snkr01g, @gianfrancobtl, @jeffreychy, @B7ackCa7, @gaminglifex, @illunis9, @kikyoluka, @rollonbears234, @ErayBarslan, @K-Konstantinidis, @amdela3079, @cmosongo, @abc0xmattyic333, @leolamera, @mmorrow8, @sr2751, @Anri-Lombard, @ajinkyabhandare, @stephenthajeb, @libingheng, @Mennodeg, @xand974, @TIMOTHYBEAN0911, @Sitaras, @Oucema90, @gritcsenko, @breathelot, @mykha8lad, @pcminh0505, @SophiaONEsource, @yuniorcc, @abhinavs, @IshikuUltra, @jpertus, @diogoFritz, @benlearnscode, @bonniegachiengu, @arjunshen0y, @tankneo, @M-A-Mohit-Khan, @kwkerstein, @alvinyap510, @whowantsmoneyman, @Klaireo, @EZ35, @Rattraper

**Comment by aldoruizluna** [comment]
Fuck off ya cunt @ZekDtonik

**Comment by moonsuyoung** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
pyrooka, @cncp20, @songroger, @new0hand, @Rolo-1001, @piotrlemen, @oreza, @yuebaiqinghui, @MattioCh, @orf53975, @RichGM, @neatori18, @DrayChou, @Bash-and-tea, @clayne, @peramsathyam, @elainte, @bnvk, @beilinhai, @ric2z, @bewakes, @coderHsc, @orange-beach, @andis-sprinkis, @mr-mosi, @demingao, @chemandy, @wjwzero, @cuyu, @AlbertWerner, @xebecnan, @ctr-e, @lastmjs, @zhoudaqing, @claudioap, @cheezberg, @0x00evil, @PPACI, @jjacobson93, @kuko126, @Triphallus, @nake13, @starkshaw, @danimesq, @leongkui, @MountVase, @egene-huang, @jameschern, @inremembert, @newreriodtilyupo, @jagarinart, @ubertidavide, @pors, @rricote, @mj-vn, @filinpavel, @Thunder33345, @DracoBlue, @nicholausgorczanycat, @stevenferrer, @kosakuraiori, @erdos, @bosioer, @renzhexigua, @indykish, @jpatel71, @bit4bit, @banesec, @Idesmi, @quiz42, @353355756, @kuczmama, @arabyalhomsi, @YaaMe, @akaralar, @neosin, @angelisochoa, @dapithor, @Coriou, @AlexGustafsson, @tgrm-tangram, @HisDudeness666, @beibei1999, @riamehdi, @Lalic, @anshuljoshi, @edouard-lopez, @targer, @wein00, @webcaetano, @lgarfield, @Mocilas, @hjc1702, @netqqnet, @linhongjun, @John-Willikers, @viperbluff, @geoboldev, @LeeReindeer
